---
rules:
    - description: Identtify security policies with deny  
      regex: deny$
      color: f#ff0000 bold

    - description: Will color (username)@(devicename)>
      regex: (^\w*)@([a-zA-Z0-9\,\-]*>) 
      color: 
          1: f#00DF3A
          2: f#00D1DB bold

    - description: Ipv4s 
      regex: \b(?<!\.)((25[0-5]|(2[0-4]|[0-1]?\d)?\d)\.){3}(25[0-5]|(2[0-4]|[0-1]?\d)?\d)(/\d+)?(?!\.)\b 
      color: f#00D1DB bold

#JUNOS
# SECURITY POLICIES
    - description: Security policies 
      regex: "(set security policies) (from-zone [a-zA-Z0-9_-]+ )(to-zone [a-zA-Z0-9_-]+ )(policy [a-zA-Z0-9_-]+ )"
      color: 
          1: f#FFFFFF
          2: f#00F969 bold
          3: f#FF0049 bold
          4: f#6CFF00 bold

    - description: Security Policies - Description 
      regex: (description ["\/a-zA-Z0-9\.\s_\*(),-]+)$ #"
      color: f#00D1DB bold

    - description: Security Policies - Match|Then
      regex: (match|then) 
      color: f#FFFFFF

    - description: Security Policies - Source-Adress
      regex: (source-address [\/a-zA-Z0-9\._-]+)?
      color: f#00F969 bold

    - description: Security Policies - Destination-Adress
      regex: (destination-address [\/a-zA-Z0-9\._-]+)?
      color: f#FF0049 bold

    - description: Security Policies - Application
      regex: (application [\/a-zA-Z0-9\._-]+)?
      color: f#03DAC6 bold

    - description: Security Policies - deny
      regex: deny$
      color: f#FF0000 bold

    - description: Security Policies - log
      regex: (log [/a-zA-Z0-9\._-]+)?$
      color: f#FF0000 bold

# BGP

# Show interface
    - description: Interface - Physical Interface 
      regex: "^Physical interface: [a-zA-Z0-9\/-]+"
      color: f#6CFF00

    - description: Interface - Physical Link Status (Up|Down)
      regex: Physical link is ((Up)|Down)
      color: 
          1: f#FF0000 bold
          2: f#6CFF00

    - description: Interface - Description 
      regex: Description:\s[a-zA-Z0-9\s_\/"-]+$ 
      color: f#6CFF00

    - description: Interface - Last Flapped 
      regex: Last flapped\s+:\s.*$ 
      color: f#00D1DB bold

    - description: Interface - Input rate (green)
      regex: Input rate\s*:\s[0-9]+ bps \([0-9]+ pps\) 
      color: f#00F969 bold

    - description: Interface - Output rate (red)
      regex: Output rate\s*:\s[0-9]+ bps \([0-9]+ pps\) 
      color: f#FF0049 bold


## ARISTA
# General
    - description: Cisco MAC Address Notation 
      regex: ([0-9a-f]{4}\.[0-9a-f]{4}\.[0-9a-f]{4}).*
      color: f#FF0049 


# Interfaces
    - description: Interface - Physical status
      regex: ((^Ethernet[0-9]+ is up)|^Ethernet[0-9]+ is down)
      color:
          1: f#ff0000 bold
          2: f#6CFF00

    - description: Interface - Line Protocol 
      regex: ((line protocol is down.*$)|(line protocol is lowerlayerdown.*$)|line protocol is up.*$)
      color:
          1: f#6CFF00
          2: f#ff0000 bold
          3: f#ff0000 bold

